services:
  - type: web
    name: portfolio
    runtime: python
    buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn MyPortfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyPortfolio.settings
      - key: PYTHON_VERSION
        value: 3.10